# -*- coding: utf-8 -*-
"""Shopping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vN62on2IKMFTxGtru9JUn6COnTZ-Bwzg
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np

st.title("Señales de Compra/Venta con MA y Modelo de Resorte")

# --- Selección del ticker ---
TICKERS = ["BTC-USD", "GAPB.MX", "PLTR", "SPY", "GRUMAB.MX", "FMTY14.MX", "IAU"]
ticker = st.selectbox("Selecciona un activo:", TICKERS)

# --- Selección del tipo de señal (último día) ---
opcion = st.selectbox(
    "Filtrar resultado (último día):",
    options=[0, 1, 2],
    format_func=lambda x: "0 = Ninguno" if x == 0 else ("1 = Compra" if x == 1 else "2 = Venta")
)

# --- Descargar datos ---
df = yf.download(ticker, period="2y", interval="1d")
df.dropna(inplace=True)

# === Medias móviles ===
df["MA5"] = df["Close"].rolling(5).mean()
df["MA10"] = df["Close"].rolling(10).mean()

# === Señales por cruce MA5 vs MA10 ===
df["Signal"] = np.where(df["MA5"] > df["MA10"], 1, 0)
df["Crossover"] = df["Signal"].diff()

# === Modelo del resorte (Hooke) ===
close_values = df["Close"].values.flatten()
ma10_values  = df["MA10"].values.flatten()

df["x"] = close_values - ma10_values  # desplazamiento
k = 0.001
df["Force"] = -k * df["x"]

# === Umbral del resorte ===
threshold = df["x"].std() * 1.5
df["Exit"] = np.where(abs(df["x"]) > threshold, 1, 0)

# === Fechas de salida y entrada usando el resorte ===
df["Exit_diff"] = df["Exit"].diff()

exit_dates = df[(df["Exit_diff"] == 1) & (df["MA5"] > df["MA10"])].index
entry_dates = df[(df["Exit_diff"] == -1) & (df["MA5"] < df["MA10"])].index

# ================================
#   ASIGNAR 1 = COMPRA / 2 = VENDE
# ================================

df["TradeSignal"] = 0   # Por defecto
df.loc[entry_dates, "TradeSignal"] = 1
df.loc[exit_dates,  "TradeSignal"] = 2

# ================================
#     FILTRAR SOLO EL ÚLTIMO DÍA
# ================================
ultimo = df.tail(1)

st.subheader("Señal del último día")
st.write(f"Ticker seleccionado: **{ticker}**")

# Filtrar por la opción elegida
if ultimo["TradeSignal"].iloc[0] == opcion:
    st.success(f"Señal del día: {opcion}")
    st.dataframe(ultimo)
else:
    st.warning(f"La señal del último día NO es {opcion}. Es {int(ultimo['TradeSignal'].iloc[0])}.")
    st.dataframe(ultimo)

# Descargar CSV completo
csv = df.to_csv().encode("utf-8")
st.download_button("Descargar CSV con Señales", csv, "senales.csv", "text/csv")