# -*- coding: utf-8 -*-
"""Shopping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vN62on2IKMFTxGtru9JUn6COnTZ-Bwzg
"""

import yfinance as yf
import pandas as pd
import numpy as np

TICKERS = ["BTC-USD", "GAPB.MX", "PLTR", "SPY", "GRUMAB.MX", "FMTY14.MX", "IAU"]

resultados = []

for ticker in TICKERS:

    df = yf.download(ticker, period="2y", interval="1d")

    if df.empty:
        continue

    # === Medias móviles ===
    df["MA5"] = df["Close"].rolling(5).mean()
    df["MA10"] = df["Close"].rolling(10).mean()

    # === Cruce ===
    df["Signal"] = np.where(df["MA5"] > df["MA10"], 1, 0)
    df["Crossover"] = df["Signal"].diff()

    # === Modelo del resorte ===
    df["x"] = df["Close"] - df["MA10"]
    k = 0.001
    df["Force"] = -k * df["x"]

    threshold = df["x"].std() * 1.5
    df["Exit"] = np.where(abs(df["x"]) > threshold, 1, 0)

    df["Exit_diff"] = df["Exit"].diff()

    last = df.iloc[-1]  # SOLO EL ÚLTIMO DATO

    # === Determinar la señal final ===
    if last["Crossover"] == 1:
        final_signal = 1  # Comprar
    elif last["Exit"] == 1:
        final_signal = 2  # Vender
    else:
        final_signal = 0  # Nada

    resultados.append({
        "Ticker": ticker,
        "Fecha": last.name,
        "Close": last["Close"],
        "MA5": last["MA5"],
        "MA10": last["MA10"],
        "x": last["x"],
        "Exit": last["Exit"],
        "Crossover": last["Crossover"],
        "Estrategia (1 Compra, 2 Venta, 0 Nada)": final_signal
    })

# === DataFrame final ===
df_final = pd.DataFrame(resultados)
df_final