# -*- coding: utf-8 -*-
"""Shopping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vN62on2IKMFTxGtru9JUn6COnTZ-Bwzg
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np

st.title("Señal Final: 1 Compra, 2 Venta, 0 Nada")

TICKERS = ["^GSPC","BTC-USD", "NVDA", "BABA", "VISTAA.MX", "DANHOS13.MX", "EDUCA18.MX",
"FIBRAMQ12.MX", "FIBRAPL14.MX", "FIHO12.MX", "FINN13.MX", "FMTY14.MX",
"FPLUS16.MX", "FSHOP13.MX", "FUNO11.MX", "ACCELSAB.MX", "AGUA.MX", "ALFAA.MX",
"ASURB.MX", "CADUA.MX", "CERAMICB.MX", "DINEB.MX", "GAPB.MX", "GCARSOA1.MX",
"GISSAA.MX", "GMD.MX", "GMXT.MX", "HOMEX.MX", "JAVER.MX", "KUOB.MX",
"OMAB.MX", "ORBIA.MX", "PASAB.MX", "PINFRAL.MX", "SITES1A-1.MX", "TMMA.MX",
"TRAXIONA.MX", "VESTA.MX", "VINTE.MX", "VOLARA.MX", "ALPEKA.MX", "AUTLANB.MX",
"CEMEXCPO.MX", "CMOCTEZ.MX", "COLLADO.MX", "CONVERA.MX", "CYDSASAA.MX",
"GCC.MX", "GMEXICOB.MX", "ICHB.MX", "LAMOSA.MX", "MFRISCOA-1.MX",
"PE&OLES.MX", "POCHTECB.MX", "SIMECB.MX", "TEAKCPO.MX", "VITROA.MX",
"AC.MX", "BIMBOA.MX", "CHDRAUIB.MX", "CUERVO.MX", "CULTIBAB.MX",
"FEMSAUBD.MX", "GIGANTE.MX", "GRUMAB.MX", "HERDEZ.MX", "KIMBERA.MX",
"KOFUBL.MX", "LACOMERUBC.MX", "MINSAB.MX", "SORIANAB.MX", "WALMEX.MX",
"BEVIDESB.MX", "FRAGUAB.MX", "LABB.MX", "MEDICAB.MX", "AMXB.MX",
"AXTELCPO.MX", "CABLECPO.MX", "CTAXTELA.MX", "MEGACPO.MX", "TLEVISACPO.MX",
"ACTINVRB.MX", "BBAJIOO.MX", "BOLSAA.MX", "CREAL.MX", "FINAMEXO.MX",
"FINDEP.MX", "GBMO.MX", "GENTERA.MX", "GFINBURO.MX", "GFNORTEO.MX",
"GNP.MX", "GPROFUT.MX", "INVEXA.MX", "PROCORPB.MX", "Q.MX", "RA.MX",
"AGUILASCPO.MX", "ALSEA.MX", "CIDMEGA.MX", "CIEB.MX", "CMRB.MX",
"HCITY.MX", "HOTEL.MX", "LIVEPOL1.MX", "NEMAKA.MX", "POSADASA.MX",
"RLHA.MX", "SPORTS.MX", "VASCONI.MX", "ARKB", "BTCW", "BTCO", "BITB",
"HODL", "EZBC", "FBTC", "BRRR", "GBTC", "DEFI", "IBIT", "ACWI",
"SPY", "FAS", "SPXL", "TECL", "IAU", "NU", "MELI", "META",
"NFLX", "IONQ", "QUBT", "QBTS", "RGTI", "PLTR", "SOFI", "HOOD"]

opcion = st.selectbox("Selecciona señal:", ["Todas", "1 Compra", "2 Venta", "0 Nada"])

resultados = []

for ticker in TICKERS:

    df = yf.download(ticker, period="1y", interval="1d")

    if df.empty:
        continue

    # === APLANAR COLUMNAS SI YFINANCE REGRESA MULTI-ÍNDICE ===
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [c[0] for c in df.columns]

    # Asegurar que Close existe
    if "Close" not in df.columns:
        st.write(f"Ticker {ticker}: No tiene columna Close")
        continue

    # === Medias Móviles ===
    df["MA5"] = df["Close"].rolling(5).mean()
    df["MA10"] = df["Close"].rolling(10).mean()

    df.dropna(inplace=True)

    # === Señales ===
    df["Signal"] = (df["MA5"] > df["MA10"]).astype(int)
    df["Crossover"] = df["Signal"].diff()

    # === Cálculo x seguro ===
    df["x"] = df["Close"].to_numpy() - df["MA10"].to_numpy()

    # === Resorte ===
    k = 0.001
    df["Force"] = -k * df["x"]

    threshold = df["x"].std() * 1.5
    df["Exit"] = (abs(df["x"]) > threshold).astype(int)
    df["Exit_diff"] = df["Exit"].diff()

    # === Último dato ===
    last = df.iloc[-1]
    prev = df.iloc[-2]

    # === Simular Exit_diff solo para el último dato ===
    exit_diff = last["Exit"] - prev["Exit"]

    # === Señales equivalentes a las de todo el DataFrame ===
    exit_signal  = (exit_diff == 1) and (last["MA5"] > last["MA10"])
    entry_signal = (exit_diff == -1) and (last["MA5"] < last["MA10"])

    # === Estrategia final ===
    if last["Crossover"] == 1 or entry_signal:
        estrategia = 1   # Compra
    elif last["Exit"] == 1 or exit_signal:
        estrategia = 2   # Venta
    else:
        estrategia = 0   # Mantener

    
    # === Último dato ===
    # last = df.iloc[-1]

    # === Estrategia final ===
     
    #if last["Crossover"] == 1:
     #   estrategia = 1  # Compra
    #elif last["Exit"] == 1:
      #  estrategia = 2  # Venta
    #else:
       # estrategia = 0
#######################################
    resultados.append({
        "Ticker": ticker,
        "Fecha": last.name,
        "Close": last["Close"],
        "Estrategia": estrategia
    })

df_final = pd.DataFrame(resultados)

# === Filtro ===
if opcion == "1 Compra":
    df_final = df_final[df_final["Estrategia"] == 1]
elif opcion == "2 Venta":
    df_final = df_final[df_final["Estrategia"] == 2]
elif opcion == "0 Nada":
    df_final = df_final[df_final["Estrategia"] == 0]

st.dataframe(df_final)


# Personalización de diseño
st.markdown("""
<style>
    .stApp {
        background-color:  #5BF58E;
    }
    .css-1d391kg {
        color:  #000000;
    }
</style>
""", unsafe_allow_html=True)
